version: 0.0.{build}-{branch}

install:  
  - cmd: cd  %APPVEYOR_BUILD_FOLDER%\src

pull_requests:
  do_not_increment_build_number: true

environment:
  QT_INSTALL_ROOT: C:\Qt\5.12.2\msvc2015_64

build_script:
- cmd: >-
    
    %QT_INSTALL_ROOT%\bin\qtenv2.bat

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    
    cd %APPVEYOR_BUILD_FOLDER%\src
    
    qmake CONFIG+=release
    
    nmake

    cd %APPVEYOR_BUILD_FOLDER%\src\tests\projectviewerwindow
    
    qmake tests.pro DESTDIR=.

    nmake

    cd %APPVEYOR_BUILD_FOLDER%\src\tests\projectviewerwindow\release

    tests.exe
     
