// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoardGame struct {
	_tab flatbuffers.Table
}

func GetRootAsBoardGame(buf []byte, offset flatbuffers.UOffsetT) *BoardGame {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoardGame{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BoardGame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoardGame) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoardGame) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func BoardGameStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BoardGameAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(description), 0)
}
func BoardGameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
